name: D3plus
navigation:
- text: Examples
  url: /examples/
- text: Documentation
  url: https://github.com/alexandersimoes/d3plus/wiki
- text: Workshops
  url: /workshops/
- text: Download
  url: /d3plus.zip
- text: Source
  url: https://github.com/alexandersimoes/d3plus

workshops:
  nav_11_19_2013:
    title: "Workshop 1: November 19th, 2013"
    links:
    - text: Intro
      url: intro
    - text: D3js
      url: d3js
    - text: Data and Attributes
      url: d3plus
    - text: Tree Map
      url: tree_map
    - text: Stacked
      url: stacked
    - text: Pie Scatter
      url: pie_scatter/
    - text: Network
      url: network
    - text: Rings
      url: rings
    - text: Future Development
      url: future

  nav_11_29_2013:
    title: "Workshop 2: November 29th, 2013"
    links:
    - text: Intro
      url: intro
    - text: SVG
      url: svg
    - text: D3js
      url: d3js
    - text: Data and Attributes
      url: d3plus
    - text: Getting Started
      url: started
    - text: Tree Map
      url: tree_map
    - text: Stacked
      url: stacked
    - text: Pie Scatter
      url: pie_scatter/
    - text: Network
      url: network
    - text: Rings
      url: rings
    - text: Future Development
      url: future