name: D3plus
navigation:
- text: Workshops
  url: /workshops/11_19_2013/intro/
# - text: Examples
#   url: /examples/
- text: Download
  url: /d3plus.v1.zip

workshop_11_19_2013_nav:
- text: Intro
  url: /workshops/11_19_2013/intro/
- text: D3js
  url: /workshops/11_19_2013/d3js/
- text: Data and Attributes
  url: /workshops/11_19_2013/d3plus/
- text: Tree Map
  url: /workshops/11_19_2013/tree_map/
- text: Stacked
  url: /workshops/11_19_2013/stacked/
- text: Network
  url: /workshops/11_19_2013/network/
- text: Rings
  url: /workshops/11_19_2013/rings/